version: "3.9"

services:
  bsc-geth:
    build: 
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/binance-chain/bsc.git
        GIT_CHECKOUT_REF: v1.1.19
    image: bsc-geth:docker-local