version: "3"

services:
  bsc-rpc: # This is the bootstrap node
    image: bsc-geth:docker-local
    env_file: .env
    ports:
      - 8545:8545
    environment:
      NODE_ID: bsc-rpc
    volumes:
      - ./storage/bsc-rpc:/root/.ethereum
      - ./scripts:/scripts
      - ./config:/config
    command: ash /scripts/bsc-rpc.sh

  bsc-validator1:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator1
      BOOTSTRAP_HOST: bsc-rpc
    volumes:
      - ./storage/bsc-validator1:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh

  netstats:
    build: ./netstats
    ports:
      - 3000:3000
    environment:
      WS_SECRET: bscpwd
    restart: always

  truffle-test:
    build: ./truffle-test
    command: /scripts/truffle-test.sh
    env_file: .env
    environment:
      RPC_HOST: bsc-rpc
      RPC_PORT: 8545
    volumes:
      - ./scripts:/scripts


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 99.99.0.0/16
